from building import *

cwd     = GetCurrentDir()
src = []

if GetDepend(['RT_RIO_CPS_GEN2']):
    src = src + ['idt_gen2.c']


CPPPATH = [cwd]
group   = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_RAPIDIO'], CPPPATH = CPPPATH)

Return('group')
